[package]
name = "netbeat"
version = "0.1.0"
edition = "2024"
description = "A fast, lightweight Rust tool for testing network upload and download speeds between a client and server."

[dependencies]
byte-unit = "5.1.6"
clap = { version = "4.5.42", features = ["derive"] }
spinners = "4.1.1"
