#!/bin/sh

echo "Running pre-commit checks..."

echo "\nRunning tests..."
cargo test

echo "\nRunning clippy..."
cargo clippy -- -D warnings

echo "\nRunning fmt..."
cargo fmt

echo "\nRunning check..."
cargo check
